---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: REPLACEME
  namespace: test
  labels:
    app: REPLACEME
spec:
  replicas: 1
  selector:
    matchLabels:
      run: REPLACEME
  template:
    metadata:
      labels:
        run: REPLACEME
    spec:
      containers:
      - name: REPLACEME
        image: varius/REPLACEME:dev
        envFrom:
          - secretRef:
              name: REPLACEME-env
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
          requests:
            memory: 256Mi
            cpu: 100m
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: REPLACEME
  namespace: test
  labels:
    app: REPLACEME
  annotations:
    networking.gke.io/internal-load-balancer-subnet: vatom-vpc-p-host-001-sub-region-ilb-001
    networking.gke.io/load-balancer-type: "Internal"
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    run: REPLACEME
  type: LoadBalancer
  externalTrafficPolicy: Cluster
